Feature/react_redux
jwhitaker/typescript-web-boilerplate pull request #3
Opened 2016-09-27 19:09 UTC by kureta

I made a React-Redux branch for your boilerplate. I had to set
```
tslint: {
        emitErrors: false,
        failOnHint: false
    }
```
because it complains about unused imports and I couldn't figure out how to fix those.

I am not exactly sure how these pull request things work but I wanted to ask you to merge this into a new `feature/react_reduce` branch. And lastly, I hope I am not bothering you with all these comments and pull requests. Have a nice day/night.

2016-09-27 19:36 UTC, jwhitaker requested changes
Take a look at https://github.com/reactjs/react-redux and examples there.  Your Counter.tsx could be simplified and broken out into separate files.

2016-09-27 19:40 UTC, jwhitaker reviewed
As well, we may want to add all the react/redux libraries to the vendor.bundle.js

2016-09-27 19:40 UTC, jwhitaker commented on package.json
> +    "jquery": "^3.1.1",
I'm wondering if jquery is even/was required at all

2016-09-27 19:41 UTC, jwhitaker commented
Not bothering me at all, I'm happy to help.

2016-09-29 02:31 UTC, kureta commented on package.json
> +    "jquery": "^3.1.1",
I think not but I'm not sure.

2016-09-29 08:59 UTC, kureta commented on package.json
> +    "jquery": "^3.1.1",
just tried it. removed jquery dependency and it complained saying that "bootstrap requires jquery". I guess it was required after all.

2016-09-29 12:15 UTC, jwhitaker commented on package.json
> +    "jquery": "^3.1.1",
Of course, I should've remembered that :)

2018-09-07 23:06 UTC, closed without merging